# Generated by Django 2.1 on 2019-10-26 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Localility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LocalilityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='app.Localility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=252)),
                ('addition_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='app.Localility')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_favor', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Proposition')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Proposition'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='localilityuser',
            unique_together={('user', 'locality')},
        ),
    ]
